### ISSUE TITLE
Analytics entries empty 

### ISSUE THREAD

**Issue by jorgesanchezperez** [OpenBankingToolkit/openbanking-analytics#163]
Ticket: [zen 51459](https://forgerock.zendesk.com/agent/tickets/51459)

For some KPI metrics the entries are empty doesn't contains any collection:
- ConsentStatusEntry: _empty_
- DirectoryCounterEntry: have collections
- EndpointUsageAggregate: have collections
- EndpointUsageEntry: _empty_
- GeoIP: _empty_
- JwtGenerationEntry: have collections
- JwtsValidationEntry: have collections
- PsuCounterEntry: _empty_
- SessionCounterEntry: have 6 collections
- TokenUsage: have collections
- TppEntry: have collections

**Comment by jorgesanchezperez** [comment]
Some metrics are not getting saved in the latest release:

- Number of PSUs is always 0, and number of endpoint calls by OpenBanking API versions is also empty
- New account consents seems to go up
- Number of new Organisations is always 0

**Comment by jorgesanchezperez** [comment]
Update all entries `Document` Objects to use the annotation `JsonDeserialize` and `JsonSerialize` to use a specific formatter class.

**Comment by BohoCode** [comment]
These need updating

- [ ] openbanking-tpp
- [x] openbanking-jwkms
- [x] openbanking-auth
- [x] openbanking-analytics
- [ ] openbanking-uk-extensions
- [ ] openbanking-aspsp
- [ ] openbanking-directory
